### PR TITLE
[R5U-1126] Track changes when values are set through forwarded methods

### LINKED ISSUE #69: .changed? not working as expected in after_save
Building a hook around an Account property I have found some unexpected behaviour. The `changed?` method does not work in the same way for a property than for an attribute in an `after_save` call. An example using one of the properties in `Account`, ip_restriction:

```
class Account
  before_save :print_changes
  after_save :print_changes

  def print_changes
    if name.changed?
      p "Name changed" 
    else
      p "Name NOT changed"
    end

    if texts.detect { |p| p.name == "ip_restriction" }.changed?
     p "IP Restriction changed"
   else
     p "IP Restriction NOT changed"
   end
  end
end

account = Account.last
account.name = "foo"
account.ip_ranges = '1.1.1.1'
account.save
=> "Name changed"
=> "IP Ranges changed"
[Save happens here]
=> "Name changed"
=> "IP Ranges NOT changed"
```

So the behavior is the expected one in `before_save`, but in `after_save` the changes to a property seem to have been committed already. Is that expected or correct somehow? Right now we are using `around_save` to circumvent this issue.

### PR DESCRIPTION
**Pull request by saturnflyer**
Fixes #69 
Addresses R5U-1126

When updating attributes, ActiveRecord needs to be notified of the incoming change.

This also removes references to the deprecated `update_attributes` methods and sets forwarded attributes on the main model using `delegate_to_property_set` as an `attribute`

### CODE REVIEW

File: lib/property_sets/delegator.rb [hunk 1]
```diff
@@ -21,10 +21,17 @@ def delegate_to_property_set(setname, mappings)
...
         mappings.each do |old_attr, new_attr|
+          if ActiveRecord.version >= Gem::Version.new('5.0')
+            attribute old_attr, ActiveModel::Type::Value.new
+          end
           define_method(old_attr) { send(setname).send(new_attr) }
           alias_method "#{old_attr}_before_type_cast", old_attr
           define_method("#{old_attr}?") { send(setname).send("#{new_attr}?") }
-          define_method("#{old_attr}=") { |value| send(setname).send("#{new_attr}=", value) }
+          define_method("#{old_attr}_will_change!"){ attribute_will_change!(old_attr) }
+          define_method("#{old_attr}=") do |value|
```
Comment (saturnflyer) [inline lib/property_sets/delegator.rb:31]: Code that calls `update_attribute` will call this setter. Without the `_will_change!` method the changes are not tracked

File: spec/property_sets_spec.rb [hunk 2]
```diff
@@ -339,6 +339,21 @@
     end
   end
 
+  describe "update_attribute" do
```
Comment (grosser) [inline spec/property_sets_spec.rb:342]: so this test would have failed before ?
... should use `update` and `update!` in the tests ?
...

File: lib/property_sets/active_record_extension.rb [hunk 3]
```diff
@@ -163,15 +163,17 @@ def association_class
...
         super
       end
+      alias update_attributes update
 
-      def update_attributes!(attributes)
+      def update!(attributes)
         update_property_set_attributes(attributes)
         super
       end
+      alias update_attributes! update!
```
[the remark this answers is not in the document]
Comment (saturnflyer) [reply lib/property_sets/active_record_extension.rb:176]: this is what rails does

File: spec/property_sets_spec.rb (hunk 2 above)
Comment (saturnflyer) [reply spec/property_sets_spec.rb:342]: I'm glad you asked this because we must have deleted the better tests before committing... Updating this

File: lib/property_sets/delegator.rb [hunk 4]
```diff
@@ -21,10 +21,17 @@ def delegate_to_property_set(setname, mappings)
         raise "Second argument must be a Hash" unless mappings.is_a?(Hash)
 
         mappings.each do |old_attr, new_attr|
+          if ActiveRecord.version >= Gem::Version.new('5.0')
+            attribute old_attr, ActiveModel::Type::Value.new
```
Comment (pschambacher) [inline lib/property_sets/delegator.rb:25]: What does this do?

Comment (srvance) [reply lib/property_sets/delegator.rb:25]: AR 5 requires that the type be declared for the attribute. This is the generic "any" type because we don't have additional information.

Comment (saturnflyer) [reply lib/property_sets/delegator.rb:27]: We need to tell ActiveRecord to track this attribute with the `attribute` method. Relevant PR and answer here https://github.com/rails/rails/issues/33753#issuecomment-417110000

File: lib/property_sets/delegator.rb (hunk 1 above)
Comment (saturnflyer) [reply lib/property_sets/delegator.rb:32]: Updated the implementation to use `super` instead, due to the use of `attribute` higher up in the file for managing this attribute.

File: lib/property_sets/delegator.rb (hunk 4 above)
Comment (pschambacher) [reply lib/property_sets/delegator.rb:27]: 👍
